#ifndef LACAN_LIMITS_BROAD_H
#define LACAN_LIMITS_BROAD_H

//LIMITES MAXIMOS DE CADA VARIABLE DEL GENERADOR

#define LACAN_VAR_BROAD_IBAT_MAX     2  //A
#define LACAN_VAR_BROAD_IBAT_MIN    -3

#define LACAN_VAR_BROAD_PO_MAX  2     //kW
#define LACAN_VAR_BROAD_PO_MIN  0     //kW

#define LACAN_VAR_BROAD_ISD_MAX   10  //A
#define LACAN_VAR_BROAD_ISD_MIN   0   //A

#define LACAN_VAR_BROAD_IO_MAX    10  //A
#define LACAN_VAR_BROAD_IO_MIN    0   //A

#define LACAN_VAR_BROAD_VO_MAX    300 //V
#define LACAN_VAR_BROAD_VO_MIN    100 //V

#endif // LACAN_LIMITS_BROAD_H
